stages:
  - test
  - build
  - images

api test:
  stage: test
  image: maven:3.9.9-amazoncorretto-21
  script:
    - cd api
    - mvn clean test
  artifacts:
    paths:
      - api/target/reports/
      - api/target/site/
      - api/target/surefire-reports/

frontend test:
  stage: test
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run lint
    - npm run coverage
  artifacts:
    paths:
      - frontend/coverage/

api build:
  stage: build
  image: maven:3.9.9-amazoncorretto-21
  script:
    - cd api
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - api/target/*.jar

frontend build:
  stage: build
  image: node:20-alpine
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

images:
  stage: images
  image: docker:latest
  services:
    - docker:dind
  script:
    - test -f "$ENV_FILE_PROD"
    - docker compose --env-file "$ENV_FILE_PROD" config
    - docker compose --env-file "$ENV_FILE_PROD" build