spring.application.name=demo
server.port=${API_PORT:3000}

spring.datasource.url=jdbc:postgresql://${TEST_DB_HOST:localhost}:${TEST_DB_PORT:5434}/${TEST_DB_NAME:cae_e2e}
spring.datasource.username=${TEST_DB_USER:cae_user}
spring.datasource.password=${TEST_DB_PASSWORD:cae}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=never
